#SWIFT_PATH = /home/gonsolo/downloads/swift-5.3.3-RELEASE-ubuntu20.04/usr/lib/swift
SWIFT_PATH = ../ci
SWIFT_LIBS_PATH = $(SWIFT_PATH)/linux
SWIFT_LIBS = -L$(SWIFT_LIBS_PATH) -lswiftSwiftOnoneSupport -lswiftCore -lFoundation -lswiftGlibc -lswiftDispatch \
             -ldispatch -lBlocksRuntime -licui18nswift -licuucswift -licudataswift

